name: classico
description: A Flutter project for AI JEE Mock Tests.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  fl_chart: ^0.66.0
  google_sign_in: ^6.1.5
  firebase_core: ^2.24.0
  firebase_database: ^10.3.0
  firebase_database_web: ^0.2.1+4
  http: ^1.1.0
  cloud_firestore: ^4.9.0
  connectivity_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^1.1.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
